### ISSUE TITLE
Can fmt be passed as char const * ?

### ISSUE THREAD

**Issue by justinmcgrath** [cropsinsilico/cis_interface#16]
The constructor for CisInput, and the cisInputFmt() function accept fmt as char*. Can that be changed to accept char const * as in the previous version? Otherwise from C++ you can't pass string literal values or use string.c_str(), and in C potentially a function could modify memory storing a string literal value.

https://github.com/cropsinsilico/cis_interface/blob/35fd50f777f89da78e9464bbc06a62bec297c9ae/cis_interface/interface/PsiInterface.hpp#L37

**Comment by langmm** [comment]
The current version of master has been changed back to use the const char format again.

**Comment by justinmcgrath** [comment]
Great. Thanks.
