### ISSUE TITLE
[enhancement] - a yaml validator

### ISSUE THREAD

**Issue by sshameer** [cropsinsilico/cis_interface#25]
Hi 

When I created my first YAML file, I made many mistakes in the syntax (eg: missing spaces, etc) and it took me while to identify the issue. 

Do you think it would be possible to create a "YAML validator" something like the validator from sbml.org (http://sbml.org/Facilities/Validator/index.jsp) ?

Keep up the good work
Cheers

**Comment by langmm** [comment]
Hello!

Yes it is definitely possible and I should be able to get that working as a CLI using cerberus. I don't have a valid SMBL file to test on. How detailed is the information output for incorrect files?

**Comment by sshameer** [comment]
Hi 

Cool! I've attached an sbml file (as text file because github does not allow xml attachments). 
[farquhar1979model.txt](https://github.com/cropsinsilico/cis_interface/files/2331882/farquhar1979model.txt)

SBML validator identifies issues such as 
- syntax errors
- if more than one object has been given the same ID or variable name
- if an undefined object/variable is being called
- any required property is undefined, etc

Keep up the good work <*Thumbs up*>
Cheers

**Comment by langmm** [comment]
Sorry for taking so long to get back to you about this, but version 0.8.7 of yggdrasil (also 0.8.7 of cis_interface, but the old name won't be supported for future versions) includes a command line option for validating yaml using 

`yggvalidate <path_to_yaml1.yml> <path_to_yaml2.yml>`

Let me know if you have an questions/comments about how to make the validation better.

 - Meagan

**Comment by sshameer** [comment]
Validator seems to be working. Thank you. I think we can close this issue now.
