### ISSUE TITLE
Message is included in output the first time get_flags() is run.

### ISSUE THREAD

**Issue by justinmcgrath** [cropsinsilico/cis_interface#39]
It's not a big deal, but the first time get_flags() is called, it outputs a message like the following.
"Creating user config file: "/home/jmcgrath/.cis_interface.cfg"

So if you have something like the following in a Makefile, it causes an error:
LDFLAGS += $(shell python -c 'from cis_interface.drivers.GCCModelDriver import get_flags; print(" ".join(get_flags()[0])))

g++: error: Creating: No such file or directory
g++: error: user: No such file or directory
g++: error: config: No such file or directory
g++: error: file:: No such file or directory
g++: error: /home/jmcgrath/.cis_interface.cfg.: No such file or directory

When you run it a second time it's fine, but is there a way to have the message printed without including it in the output, so that it works the first time?

**Comment by langmm** [comment]
Hey so the print message is only the first time that cis_interface is *ever* imported by python and it is in the stdout and not the value returned by get_flags. However, I have a fix for this by moving the print message into a log so now it is not in stdout. I also have a fix for the issue with cisccflags and cisldflags where they weren't being directed to stdout, but you'll still have the issue with trying to pipe the output if there are any other messages.

**Comment by justinmcgrath** [comment]
Thanks.
