### ISSUE TITLE
Fortran support

### ISSUE THREAD

**Issue by berceanu** [cropsinsilico/cis_interface#43]
Hi, I got here from the SciPy talk. I am a physicist and find that this package can be very useful in our field, as we are usually dealing with different packages written in various languages: C, C++ and Fortran being the most prominent. I see you already support the first 2, how can I get involved with adding Fortran support?

**Comment by langmm** [comment]
Hello and welcome!

I am happy to hear that this package might be of use to your work. I have received a few requests for outlines on how to get started so I am planning to put together a guide for developing the necessary tools for supporting an additional language that I should be able to put out after the winter break. The basic pieces that are needed are:

1. Driver for compiling/running models written in the language. This would be the first step and only requires a simple hello world test program in fortran.
2. Language API. This includes methods for connecting to communication channels, serializing messages in the correct format (we are in the process of switching to use an extended form of JSON), and then methods for sending/receiving via IPC and/or ZMQ. There are existing tools for JSON serialization and ZMQ communication so this shouldn't be too difficult, but will require additional information about the serialization format.

Once I have a more format write up after break, I can point you in that direction. I'm also happy to answer any questions you have in the mean time and would enjoy hearing about the application you have in mind. My background is in astronomy & astrophysics.

 - Meagan

**Comment by langmm** [comment]
Fortran support was added in PR #61 which will be part of the next release (1.3.0). It specifically requires compiling with Fortran 2003 standards to make use of iso_c_binding. A version that allows strict Fortran 77 and/or 90 may be explored in the future.
